### ISSUE TITLE
Crash in check_puppet_agent.events

### ISSUE THREAD

**Issue by m4c3** [allangood/check_mk#10]
Can you have a look a this?

Operating System    `el6`
Check_MK Version    `1.2.8p9`
Python Version `2.6.6 (r266:84292, Jul 23 2015, 15:22:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]`
Exception `UnboundLocalError (local variable 'failures' referenced before assignment)`
Traceback    

```
 File "/omd/sites/cmk/share/check_mk/modules/check_mk_base.py", line 1468, in do_all_checks_on_host
    result = sanitize_check_result(check_function(item, params, info), check_uses_snmp(checkname))

  File "/omd/sites/cmk/local/share/check_mk/checks/check_puppet_agent.include", line 85, in check_puppet_agent_events
    if failures > crit:
```

Local Variables 

```
{'crit': 5,
 'info': [[u'last_run:', u'1474546024']],
 'item': u'Events Failure',
 'line': [u'last_run:', u'1474546024'],
 'params': (2, 5),
 'warn': 2}
```

**Comment by allangood** [comment]
Hi, thank you for your feedback.

Some variables are declared only inside the "IF" statement.
Now is corrected!
Please, upgrade to version 1.3 of plugin.

Thank you.
