### ISSUE TITLE
check_bind9 issue

### ISSUE THREAD

**Issue by str1k3r** [allangood/check_mk#12]
The plugin was successfully installed (MKP package + local agent installation) But I'm unable to activate host check changes after successful check discovery. Getting that error:
"Error: Error precompiling checks for host %HOST%: Cannot find check file dns needed for check type dns

check_mk_agent test command works without any issues.

I'm using Check_MK RAW 1.2.8p11

**Comment by allangood** [comment]
I made some changes on plugin, could you install and test the latest version?
Thank you.

**Comment by str1k3r** [comment]
@allangood now it works. thanks!
