### ISSUE TITLE
HowTo

### ISSUE THREAD

**Issue by grego1981** [allangood/check_mk#13]
Hello, I've installed the dfs check package and the agent plugin to the server, but whatever I'm trying I cannot find it in WATO or in the host inventory so as to enable it. Is there a howto or instructions as how to do it?

Thank you
Gregory

**Comment by allangood** [comment]
All information you need is on check_mk agent plugin (that script you put
on Windows server).
Basically you need to start the check_mk agent with a DOMAIN account with
privileges to get informations from DFS servers.

Regards.

**Comment by grego1981** [comment]
Good morning and thank you for your reply,

I have given the agent service the required credentials and still the service is not discovered in WATO. Specificaly I have followed the procedure below:
- Copied the  dfs_state.vbs in the plugins directory of the agent
- Given the agent service a privileged account to start with (even a domain admin account)
- restarted the agent service
- Installed the mpk file and verified its installation:
  OMD[a1]:~$ check_mk -L | grep dfs
  dfs_backlog                                  tcp    (no man page present)
  dfs_state                                    tcp    (no man page present)
- rescheduled service discovery for the host

No new service appeared on the host
Just for debug purposes I telnet on the agent port from the check_mk server and got correct output from the dfs_state check

<<<_dfs_state_>>>
90   4
70   4
60  4
27   4
25  4
85   4
12   4
91   4
20   4
105   4
40   4
00  4
30  4
101   4
50   4
100   4
10   4
45   4

Still no service....

Any thoughts?

Thank you and best regards.

Gregory

**Comment by allangood** [comment]
Hi Gregory,

Could you send the complete output from agent plugin? Sure, you can remove
all confidential information.

Thank you.

**Comment by grego1981** [comment]
Hello,

Following the results of check_mk_agent.exe test command

<<<check_mk>>>
Version: 1.2.6p12
BuildDate: Sep 18 2015
Architecture: 64bit
AgentOS: windows
Hostname: myhost
WorkingDirectory: C:\Program Files (x86)\check_mk
ConfigFile: C:\Program Files (x86)\check_mk\check_mk.ini
AgentDirectory: C:\Program Files (x86)\check_mk
PluginsDirectory: C:\Program Files (x86)\check_mk\plugins
SpoolDirectory: C:\Program Files (x86)\check_mk\spool
LocalDirectory: C:\Program Files (x86)\check_mk\local
ScriptStatistics: Plugin C:0 E:0 T:0 Local C:0 E:0 T:0
OnlyFrom: 127.0.0.1/32 10.10.99.3/32
<<<uptime>>>
19970104
<<<df>>>
C:\ NTFS 62912508 37929292 24983216  61% C:\
store1 NTFS 1258157048 710104696 548052352  57% E:\
<<ps:sep(9)>>
(\example\administrator,87628,5152,0,956,4096,13572087,24336156,254,10)
taskeng.exe
(\example\administrator,58240,3528,0,2064,3548,6240040,11700075,90,3)
dwm.exe
(\example\administrator,311440,102172,0,3328,121144,254395666731,1221452729775
,1541,18)       explorer.exe
(\example\administrator,404644,14112,0,3544,34920,203737306,105300675,282,13)
wsc.exe
(\example\administrator,108772,4624,0,3576,8736,421358701,800441131,143,8)
PccNTMon.exe
(\example\administrator,58180,2004,0,2532,1416,3744024,4368028,34,1)
 conime.e
xe
(\example\administrator,95736,11160,0,6740,4960,6589482240,3907669049,129,5)
vmtoolsd.exe
(\example\administrator,79816,8208,0,6100,3140,936006,1092007,151,5)
 rdpclip.
exe
(\example\administrator,16980,2504,0,3016,4168,0,156001,22,1) cmd.exe
(\example\administrator,72460,6204,0,6692,3212,0,156001,90,3) wuauclt.exe
(\example\administrator,54140,4460,0,6992,4000,0,780005,184,1)
 check_mk
_agent.exe
(\example\administrator,2384,104,0,2844,304,0,0,1,1)  more.com
(SYSTEM,0,0,0,0,0,0,0,0,2)      System Idle Process
<<<mem>>>
MemTotal:     6290012 kB
MemFree:      2845324 kB
SwapTotal:    6517364 kB
SwapFree:     6604516 kB
PageTotal:    12807376 kB
PageFree:     9449840 kB
VirtualTotal: 8589934464 kB
VirtualFree:  8589880324 kB
<<fileinfo:sep(124)>>
1477604580
<<<services>>>
AeLookupSvc running/auto Application Experience
ALG stopped/demand Application Layer Gateway Service
Appinfo stopped/demand Application Information
AppMgmt stopped/demand Application Management
aspnet_state stopped/demand ASP.NET State Service
AudioEndpointBuilder stopped/demand Windows Audio Endpoint Builder
AudioSrv stopped/demand Windows Audio
BFE running/auto Base Filtering Engine
BITS running/demand Background Intelligent Transfer Service
Browser stopped/disabled Computer Browser
CertPropSvc running/demand Certificate Propagation
Check_MK_Agent running/auto Check_MK_Agent
clr_optimization_v2.0.50727_32 stopped/disabled Microsoft .NET Framework
NGEN v2
.0.50727_X86
clr_optimization_v2.0.50727_64 stopped/disabled Microsoft .NET Framework
NGEN v2
.0.50727_X64
clr_optimization_v4.0.30319_32 stopped/auto Microsoft .NET Framework NGEN
v4.0.3
0319_X86
clr_optimization_v4.0.30319_64 stopped/auto Microsoft .NET Framework NGEN
v4.0.3
0319_X64
COMSysApp running/demand COM+ System Application
CryptSvc running/auto Cryptographic Services
CscService stopped/disabled Offline Files
DcomLaunch running/auto DCOM Server Process Launcher
Dhcp running/auto DHCP Client
Dnscache running/auto DNS Client
dot3svc stopped/demand Wired AutoConfig
DPS running/auto Diagnostic Policy Service
EapHost stopped/demand Extensible Authentication Protocol
EventLog running/auto Windows Event Log
EventSystem running/auto COM+ Event System
FCRegSvc stopped/demand Microsoft Fibre Channel Platform Registration
Service
fdPHost running/demand Function Discovery Provider Host
FDResPub stopped/demand Function Discovery Resource Publication
FontCache running/auto Windows Font Cache Service
FontCache3.0.0.0 running/demand Windows Presentation Foundation Font Cache
3.0.0
.0
FusionInventory-Agent running/auto FusionInventory Agent
gpsvc running/auto Group Policy Client
hidserv stopped/demand Human Interface Device Access
hkmsvc stopped/demand Health Key and Certificate Management
idsvc stopped/demand Windows CardSpace
IKEEXT running/auto IKE and AuthIP IPsec Keying Modules
IPBusEnum stopped/disabled PnP-X IP Bus Enumerator
iphlpsvc running/auto IP Helper
KeyIso stopped/demand CNG Key Isolation
KtmRm running/auto KtmRm for Distributed Transaction Coordinator
LanmanServer running/auto Server
LanmanWorkstation running/auto Workstation
lltdsvc stopped/demand Link-Layer Topology Discovery Mapper
lmhosts running/auto TCP/IP NetBIOS Helper
MMCSS stopped/demand Multimedia Class Scheduler
MpsSvc running/auto Windows Firewall
MSDTC running/auto Distributed Transaction Coordinator
MSiSCSI stopped/demand Microsoft iSCSI Initiator Service
msiserver stopped/demand Windows Installer
napagent stopped/demand Network Access Protection Agent
Netlogon running/auto Netlogon
Netman running/demand Network Connections
NetMsmqActivator stopped/disabled Net.Msmq Listener Adapter
NetPipeActivator stopped/disabled Net.Pipe Listener Adapter
netprofm running/auto Network List Service
NetTcpActivator stopped/disabled Net.Tcp Listener Adapter
NetTcpPortSharing stopped/disabled Net.Tcp Port Sharing Service
NlaSvc running/auto Network Location Awareness
nsi running/auto Network Store Interface Service
ntrtscan running/auto Trend Micro Security Agent RealTime Scan
PeerDistSvc stopped/demand BranchCache
PerfHost stopped/demand Performance Counter DLL Host
pla stopped/demand Performance Logs & Alerts
PlugPlay running/auto Plug and Play
PolicyAgent running/auto IPsec Policy Agent
ProfSvc running/auto User Profile Service
ProtectedStorage stopped/demand Protected Storage
RasAuto stopped/demand Remote Access Auto Connection Manager
RasMan running/demand Remote Access Connection Manager
RemoteAccess stopped/disabled Routing and Remote Access
RemoteRegistry running/auto Remote Registry
RpcLocator stopped/demand Remote Procedure Call (RPC) Locator
RpcSs running/auto Remote Procedure Call (RPC)
RSoPProv stopped/demand Resultant Set of Policy Provider
sacsvr stopped/demand Special Administration Console Helper
SamSs running/auto Security Accounts Manager
SCardSvr stopped/demand Smart Card
Schedule running/auto Task Scheduler
SCPolicySvc stopped/demand Smart Card Removal Policy
seclogon running/auto Secondary Logon
SENS running/auto System Event Notification Service
SessionEnv running/demand Terminal Services Configuration
SharedAccess stopped/disabled Internet Connection Sharing (ICS)
ShellHWDetection running/auto Shell Hardware Detection
slsvc running/auto Software Licensing
SLUINotify stopped/demand SL UI Notification Service
SNMPTRAP stopped/demand SNMP Trap
Spooler running/auto Print Spooler
SSDPSRV stopped/disabled SSDP Discovery
SstpSvc running/demand Secure Socket Tunneling Protocol Service
swprv stopped/demand Microsoft Software Shadow Copy Provider
SysMain stopped/disabled Superfetch
TapiSrv running/demand Telephony
TBS stopped/auto TPM Base Services
TermService running/auto Terminal Services
Themes stopped/disabled Themes
THREADORDER stopped/demand Thread Ordering Server
TMBMServer running/demand Trend Micro Unauthorized Change Prevention Service
TmCCSF running/demand Trend Micro Common Client Solution Framework
tmlisten running/auto Trend Micro Security Agent Listener
TmPfw running/demand Trend Micro Security Agent Firewall
TmProxy running/demand Trend Micro Security Agent NT Proxy Service
TrkWks running/auto Distributed Link Tracking Client
TrustedInstaller running/auto Windows Modules Installer
UI0Detect stopped/demand Interactive Services Detection
UmRdpService running/demand Terminal Services UserMode Port Redirector
upnphost stopped/disabled UPnP Device Host
UxSms running/auto Desktop Window Manager Session Manager
vds stopped/demand Virtual Disk
VMUSBArbService running/auto VMware USB Arbitration Service
W32Time running/auto Windows Time
WatchGuard_Authentication_Client running/auto WatchGuard Authentication
Client
WcsPlugInService stopped/demand Windows Color System
WdiServiceHost stopped/demand Diagnostic Service Host
WdiSystemHost running/demand Diagnostic System Host
Wecsvc stopped/demand Windows Event Collector
wercplsupport stopped/demand Problem Reports and Solutions Control Panel
Support
WerSvc running/auto Windows Error Reporting Service
WinHttpAutoProxySvc stopped/demand WinHTTP Web Proxy Auto-Discovery Service
Winmgmt running/auto Windows Management Instrumentation
WinRM running/auto Windows Remote Management (WS-Management)
wmiApSrv stopped/demand WMI Performance Adapter
WPDBusEnum stopped/demand Portable Device Enumerator Service
wuauserv running/auto Windows Update
wudfsvc stopped/demand Windows Driver Foundation - User-mode Driver
Framework
DFSR running/auto DFS Replication
dfs running/auto DFS Namespace
Zabbix_Agent running/auto Zabbix Agent
VMTools running/auto VMware Tools
vmvss stopped/demand VMware Snapshot Provider
WPFFontCache_v0400 stopped/demand Windows Presentation Foundation Font
Cache 4.0
.0.0
<<<winperf_phydisk>>>
1477604625.88 234
3 instances: 0_C: 1_E: _Total
-36 0 0 0 rawcount
-34 1612350356000 1545140459000 1578745407500 type(20570500)
-34 131220782258786443 131220782258786443 131220782258786443 type(40030500)
1166 1612350356000 1545140459000 3157490815000 type(550500)
-32 990893812000 1157695140000 1074294476000 type(20570500)
-32 131220782258786443 131220782258786443 131220782258786443 type(40030500)
1168 990893812000 1157695140000 2148588952000 type(550500)
-30 621456544000 387445319000 504450931500 type(20570500)
-30 131220782258786443 131220782258786443 131220782258786443 type(40030500)
1170 621456544000 387445319000 1008901863000 type(550500)
-28 2308592262027 2212359921724 4520952183751 average_timer
-28 88279061 41143889 129422950 average_base
-26 1418779596110 1657608739964 3076388336074 average_timer
-26 35835326 32799985 68635311 average_base
-24 889812665916 554751181759 1444563847675 average_timer
-24 52443735 8343904 60787639 average_base
-22 88279061 41143889 129422950 counter
-20 35835326 32799985 68635311 counter
-18 52443735 8343904 60787639 counter
-16 2306394317312 3522638720512 5829033037824 bulk_count
-14 1003375116288 1258923327488 2262298443776 bulk_count
-12 1303019201024 2263715393024 3566734594048 bulk_count
-10 2306394317312 3522638720512 5829033037824 average_bulk
-10 88279061 41143889 129422950 average_base
-8 1003375116288 1258923327488 2262298443776 average_bulk
-8 35835326 32799985 68635311 average_base
-6 1303019201024 2263715393024 3566734594048 average_bulk
-6 52443735 8343904 60787639 average_base
1248 198700609121000 198762205981000 198731407551000 type(20570500)
1248 131220782258786443 131220782258786443 131220782258786443 type(40030500)
1250 4501484 2187178 6688662 counter
<<<winperf_processor>>>
1477604625.89 238
3 instances: 0 1 _Total
-232 191794695777297 193520052641206 192657374209251 100nsec_timer_inv
-96 5473121299886 3850304049278 4661712674582 100nsec_timer
-94 2433690324479 2328380445420 2381035384949 100nsec_timer
-90 3359673891 247153790 3606827681 counter
458 2704121334 307841453330 155272787332 100nsec_timer
460 11635802588 17155897973 14395850280 100nsec_timer
1096 1471526910 2168106381 3639633291 counter
1098 1 2 3 rawcount
1508 191794695777297 193520052641206 192657374209251 100nsec_timer
1510 49285219528232 67590775883394 58437997705813 100nsec_timer
1512 0 0 0 100nsec_timer
1514 0 0 0 100nsec_timer
1516 1354170876 2172457391 3526628267 bulk_count
1518 0 0 0 bulk_count
1520 0 0 0 bulk_count
<<<winperf_if>>>
1477604625.92 510
1 instances: vmxnet3_Ethernet_Adapter
-122 1635020271386 bulk_count
-110 1773515745 bulk_count
-244 1136153178 bulk_count
-58 637362567 bulk_count
10 10000000000 large_rawcount
-246 1451101766393 bulk_count
14 1125893572 bulk_count
-16 2306394317312 3522638720512 5829033037824 bulk_count
-14 1003375116288 1258923327488 2262298443776 bulk_count
-12 1303019201024 2263715393024 3566734594048 bulk_count
-10 2306394317312 3522638720512 5829033037824 average_bulk
-10 88279061 41143889 129422950 average_base
-8 1003375116288 1258923327488 2262298443776 average_bulk
-8 35835326 32799985 68635311 average_base
-6 1303019201024 2263715393024 3566734594048 average_bulk
-6 52443735 8343904 60787639 average_base
1248 198700609121000 198762205981000 198731407551000 type(20570500)
1248 131220782258786443 131220782258786443 131220782258786443 type(40030500)
1250 4501484 2187178 6688662 counter
<<<winperf_processor>>>
1477604625.89 238
3 instances: 0 1 _Total
-232 191794695777297 193520052641206 192657374209251 100nsec_timer_inv
-96 5473121299886 3850304049278 4661712674582 100nsec_timer
-94 2433690324479 2328380445420 2381035384949 100nsec_timer
-90 3359673891 247153790 3606827681 counter
458 2704121334 307841453330 155272787332 100nsec_timer
460 11635802588 17155897973 14395850280 100nsec_timer
1096 1471526910 2168106381 3639633291 counter
1098 1 2 3 rawcount
1508 191794695777297 193520052641206 192657374209251 100nsec_timer
1510 49285219528232 67590775883394 58437997705813 100nsec_timer
1512 0 0 0 100nsec_timer
1514 0 0 0 100nsec_timer
1516 1354170876 2172457391 3526628267 bulk_count
1518 0 0 0 bulk_count
1520 0 0 0 bulk_count
<<<winperf_if>>>
1477604625.92 510
1 instances: vmxnet3_Ethernet_Adapter
-122 1635020271386 bulk_count
-110 1773515745 bulk_count
-244 1136153178 bulk_count
-58 637362567 bulk_count
10 10000000000 large_rawcount
-246 1451101766393 bulk_count
14 1125893572 bulk_count
16 10060346 bulk_count
18 199260 large_rawcount
20 0 large_rawcount
22 0 large_rawcount
-4 183918504993 bulk_count
26 636374686 bulk_count
28 987881 bulk_count
30 0 large_rawcount
32 0 large_rawcount
34 0 large_rawcount
<<<logwatch>>>
[[[Application]]]
[[[DFS Replication]]]
[[[HardwareEvents]]]
[[[Internet Explorer]]]
[[[Key Management Service]]]
[[[Security]]]
[[[System]]]
[[[Windows PowerShell]]]
<<<logwatch>>>
<<<>>>
<<<dfs_state>>>
folder  4
folder  4
folder  4
folder  4
folder  4
folder  4
folder  4
folder  4

<<<>>>
<<<local>>>
<<<mrpe>>>
<<<systemtime>>>
1477604681

Thank you and best regards

**Comment by allangood** [comment]
Hi Gregory,

Sorry for the late. Your output plugins seems to be ok for me. No problem
with it.
It was mkp package installed ok?

Do you have an OMD installation or a bare MK?

**Comment by grego1981** [comment]
Hello, 
I have an OMD installation ontop of a Centos system also tested it on another site with OMD installed on ubuntu...
I have installed the package using check_mk -P install check_dfs_state-1.2.mkp which reported no problems, I have verified it is installed by running check_mk -L which includes the command

dfs_state                                    tcp    (no man page present)

But when running  cmk --checks=dfs_state -I FS01 it outputs nothing.

**Comment by allangood** [comment]
Could you put a "--debug" after the cmk command, please?

If is not asking too much, is possible to do a ssh or any remote access to
help you with this?

**Comment by grego1981** [comment]
The --debug in the command still returns an empty response
OMD[a1]:~$ cmk --debug --checks=dfs_state -I FS01
OMD[a1]:~$
If you want I can give you access via Teaamviewer to my PC where I have an active SSH session to the server. you can contact me via email if you want aladou.web @ gmail.com

Thank you very much!

**Comment by grego1981** [comment]
I would like to publicy say THANK YOU! You are awesome Allan!

**Comment by allangood** [comment]
Thank you Gergory! You are more than welcome!
Correction will be commited soon.
