### ISSUE TITLE
applied configuration as metioned but getting python dump

### ISSUE THREAD

**Issue by aloksingh1980** [allangood/check_mk#14]
Exception in icon plugin!
Traceback (most recent call last): File "/omd/sites/DC/share/check_mk/web/plugins/views/painters.py", line 150, in paint_icons output += icon_output TypeError: coercing to Unicode: need string or buffer, tuple found

i am a old user of guacamole and tried to use your plugin but getting above error pls guide me if i am setting it wrong

**Comment by allangood** [comment]
Hi,

I need your check_mk and plugin version, please.

Thank you!

**Comment by aloksingh1980** [comment]
the check_mk version is 1.2.6p16 and the plugin version is 1.2.8

**Comment by allangood** [comment]
The latest version of the plugin is not compatible with < 1.2.8 versions of Check_MK.
If you want to use the 1.3 (latest version) of the plugin, you must use a version 1.2.8 or above of Check_MK.

But, you can modify the plugin to work with your version of Check_MK:

Edit the "remote_access.py" file:

```
Find the plugin location:
find /opt/omd/YOUR_SITE_NAME/ -name "remote_access.py"

vi or nano and change:

This line:
return 'krfb', 'Remote Access', url

For this line:
return u'<a href="%s" target="_blank" title="Remote Access">' \
        '<img class=icon src="images/icons/krfb.png"/></a>' % (url)
```
