### ISSUE TITLE
Can't install 1.4

### ISSUE THREAD

**Issue by tgm4883** [allangood/check_mk#18]
Can't install puppet-1.4.mkp.

I don't know a ton about making plugins, but I believe the issue is here https://github.com/allangood/check_mk/blob/master/plugins/puppet/info#L5

The error I get is "tar: plugins/windows/mk_puppet: Not found in archive". Looking at the repository, the file is actually named mk_puppet.ps1

**Comment by tgm4883** [comment]
I've verified that extracting the mkp, changing that line in the info file to include the .ps1 extension, tarring the files back up into a 1.4.1 mkp file now lets me install the plugin.

This is on Check_MK 1.2.8.

**Comment by allangood** [comment]
Thank you, I will revised it.

**Comment by allangood** [comment]
Sorry for this long delay.
Package corrected.

Thank you!
