### ISSUE TITLE
Check_mk 2.00 issue

### ISSUE THREAD

**Issue by grego1981** [allangood/check_mk#27]
Hi!

I've just upgraded to v2.00 so as to take advantage of the new features of check_mk but the plugin does not work.. I get the error:

Unknow DFS state

Is there a workaround to make it work again?

Thank you!

**Comment by allangood** [comment]
These check_mk plugins are not maintained anymore.
I have migrated everything to Prometheus and I don't have any check_mk instance to test anymore.
