### ISSUE TITLE
snmp_scan function on overland checks

### ISSUE THREAD

**Issue by schoekek** [allangood/check_mk#3]
pls insert snmp_scan function in check_overland checks:

```
'snmp_scan_function':   lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.3351"),
```

thx

**Comment by allangood** [comment]
Hello!

Sure! Thanks to remember me! :D

On Wed, Apr 13, 2016 at 10:14 AM, Karsten Schöke notifications@github.com
wrote:

> pls insert scnmp_scan function:
> 
> 'snmp_scan_function':   lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.3351"),
> 
> thx
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/allangood/check_mk/issues/3

## 

Use cópia oculta (BCC ou CCO) e apague dados pessoais no campo da mensagem
ao encaminhar qualquer e-mail.

http://allan.cassaro.googlepages.com

**Comment by allangood** [comment]
All snmp_scan functions are now implemented.
