### ISSUE TITLE
doesnt work in check_mk 1.2.8

### ISSUE THREAD

**Issue by FinalX92** [allangood/check_mk#5]
is it posible to make this work in 1.2.8
i cannot add the ip of the host i can see the icon

**Comment by allangood** [comment]
Yes, it's possible. But 1.2.8 still beta until now.
I have a version of all plugins working on 1.2.8b9, but I'm waiting a stable check_mk release.
Until now, this version broke compatibility with 1.2.6 version.

**Comment by FinalX92** [comment]
Can u share the beta of ur pluggin?? For the 1.2.8?

**Comment by FinalX92** [comment]
Since i saw they started working already on 1.2.9

**Comment by allangood** [comment]
If you look at http://mathias-kettner.com/check_mk_download.php, you will see all releases:
Last stable: 1.2.6p16
Last Beta: 1.2.8b13

I will wait they release the 1.2.8 as stable before upload my modifications. I don't want to break anything or open a new branch to a specific release.

**Comment by allangood** [comment]
The only modification necessary is add a function like this:

```
def is_inline_snmp_host(arg):
    return False
```

Into SNMP check_plugins.
But this will break the compatibility with 1.2.6 and prior version of check_mk.

**Comment by allangood** [comment]
Check new version! :)
