### ISSUE TITLE
Cannot find check file dfs_state needed for check type dfs_state

### ISSUE THREAD

**Issue by geertcools** [allangood/check_mk#6]
When I install the packet and start using it on my Hosts 
I see the following error message

OMD[master]:/tmp$ check_mk -R
Generating configuration for core (type nagios)...OK
Validating Nagios configuration...OK
Precompiling host checks...Error precompiling checks for host DFS_TEST_HOST: Cannot find check file dfs_state needed for check type dfs_state
OMD[master]:/tmp$

I'm able to resolve the issue by renaming check_dfs_state -> dfs_state 

mv /omd/sites/master/local/share/check_mk/checks/check_dfs_state /omd/sites/master/local/share/check_mk/checks/dfs_state

**Comment by allangood** [comment]
Please, send more details:
OMD and Check_MK version and Plugin version.

This not happening on my test environment.

**Comment by geertcools** [comment]
Ah sorry, forgot to give you the information.

Will do it, when I'm back home from holiday.

Grz
Geert

On Tuesday, 21 June 2016, Allan Gomes GooD notifications@github.com wrote:

> Closed #6 https://github.com/allangood/check_mk/issues/6.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/allangood/check_mk/issues/6#event-699571350, or mute
> the thread
> https://github.com/notifications/unsubscribe/AFu8VWfGmkN9UiZ0Rc_-fhO3h2OS48ZYks5qOD_3gaJpZM4I0hkE
> .

## 

Grz
Geert

**Comment by geertcools** [comment]
OMD - Open Monitoring Distribution Version 1.2.8p1.cre
check_mk version 1.2.8p1

OMD[master]:~$ check_mk -P show check_dfs_state
Package file:                  /omd/sites/master/var/check_mk/packages/check_dfs_state
Name:                          check_dfs_state
Version:                       1.2

**Comment by S0548692** [comment]
no solution for that problem?
