### ISSUE TITLE
it does open in a shell now

### ISSUE THREAD

**Issue by FinalX92** [allangood/check_mk#7]
hello, 

is it posible to change the remote controll to not open in check_mk shell
we are using a database with loggins and when its running in a shell it does not work.
i would like to have it like before that was awesome.

can u help me out?

ty in advance

**Comment by allangood** [comment]
Remote control? I don't have any plugin called remote control.
Could you explain better what problem on what specific plugin, please.

**Comment by FinalX92** [comment]
remote_access

is the exact name

**Comment by FinalX92** [comment]
Before ur pluggin when in the host u putted http://192.168.1.1/ when pressing remote button it went to the website now it does open in check_mk(in a shell)  i want it to go to http://192.168.1.1/ so my password manager regonize the website and fill in the user and password like in the 1.2.6 version

**Comment by FinalX92** [comment]
im gonna explain better with pictures
check_mk 1.2.6
http://i64.tinypic.com/16k40n7.png
http://i68.tinypic.com/4kbuxg.png
http://i67.tinypic.com/2je5pb8.png

check_mk 1.2.8
http://i65.tinypic.com/zt6t6g.png
http://i68.tinypic.com/33v0k60.png
http://i63.tinypic.com/2gseadd.png

so this is basicly my issue,
do u know or can tell me what i can change to not open it in an check_mk shell?

ty in advance

**Comment by allangood** [comment]
Hi FinalX92,

Now I understood your issue. Yes, this is a know problem without solution until now.
This new interface/api of check_mk opens link inside the same frame.

A workaround is press the "control" button while click on remote link. This will force the link to open on a new tab in any browser.

Working in progress with this, but without a solution until now.

Thanks for your time and patience.
