### ISSUE TITLE
[detect_virtual] Doesn't work with Proxmox 4.4

### ISSUE THREAD

**Issue by erdoking** [allangood/check_mk#9]
I testest the plugin with KVM and LXC. 

KVM:
[root@omd tmp]# bash detect_virtualization
<<<lnx_detect_virtual>>>
Manufacturer : 
Model : Standard PC (i440FX + PIIX, 1996)
BIOSVersion : 

LXC:
root@mailer:/tmp# bash detect_virtualization
/dev/mem: No such file or directory
/dev/mem: No such file or directory
/dev/mem: No such file or directory
<<<lnx_detect_virtual>>>
Manufacturer :
Model :
BIOSVersion :
IsVirtualMachine : False

**Comment by allangood** [comment]
Hi, thank you for your feed back!

Well, LXC is a different concept of virtualization (container) and doesn't have all environment inside the container itself. Due to this, many binaries and /dev files are missing. The ideal, in this case, is make a plugin inside the Host server and detect the containers, not the opposite.

About the KVM, the output looks odd... The first output line is "<<>>" and must be "<<<lnx_detect_virtual>>>" or "<<<win_detect_virtual:something>>>".

What version of plugin are you using? Your KVM machine is Linux or Windows? If Linux, are you executing the check_mk_agent as root and the "dmidecode" is installed?

Thank you.

**Comment by erdoking** [comment]
I don't understand what happens yesterday ...

kvm:
[root@omd tmp]# bash detect_virtualization
<<<lnx_detect_virtual>>>
Manufacturer : 
Model : Standard PC (i440FX + PIIX, 1996)
BIOSVersion : 
IsVirtualMachine : False

I think this looks a little bit better.
I use 3 KVM-machines and about 30 LXC's ... i think your famous plugin isn't the best for me :(

---

I used the current script-version from git.
Linux: CentOS Linux release 7.2.1511 (Core)

I run the script without checkmk-agent (for debugging)

---

For your debugging:

[root@omd tmp]# dmidecode -s baseboard-manufacturer
[root@omd tmp]# dmidecode -s system-product-name
Standard PC (i440FX + PIIX, 1996)
[root@omd tmp]# dmidecode -s baseboard-version
[root@omd tmp]# dmidecode -s system-manufacturer
QEMU

---

kvm:
[root@omd tmp]# dmidecode 

# dmidecode 2.12-dmifs

SMBIOS 2.8 present.
9 structures occupying 411 bytes.
Table at 0x000F6A10.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
        Vendor: SeaBIOS
        Version: rel-1.9.1-0-gb3ef39f-prebuilt.qemu-project.org
        Release Date: 04/01/2014
        Address: 0xE8000
        Runtime Size: 96 kB
        ROM Size: 64 kB
        Characteristics:
                BIOS characteristics not supported
                Targeted content distribution is supported
        BIOS Revision: 0.0

Handle 0x0100, DMI type 1, 27 bytes
System Information
        Manufacturer: QEMU
        Product Name: Standard PC (i440FX + PIIX, 1996)
        Version: pc-i440fx-2.6
        Serial Number: Not Specified
        UUID: 8B94F06D-7159-452D-800E-09DB7359AE46
        Wake-up Type: Power Switch
        SKU Number: Not Specified
        Family: Not Specified

Handle 0x0300, DMI type 3, 21 bytes
Chassis Information
        Manufacturer: QEMU
        Type: Other
        Lock: Not Present
        Version: pc-i440fx-2.6
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Boot-up State: Safe
        Power Supply State: Safe
        Thermal State: Safe
        Security Status: Unknown
        OEM Information: 0x00000000
        Height: Unspecified
        Number Of Power Cords: Unspecified
        Contained Elements: 0

Handle 0x0400, DMI type 4, 42 bytes
Processor Information
        Socket Designation: CPU 0
        Type: Central Processor
        Family: Other
        Manufacturer: QEMU
        ID: 61 0F 00 00 FF FB 8B 07
        Version: pc-i440fx-2.6
        Voltage: Unknown
        External Clock: Unknown
        Max Speed: 2000 MHz
        Current Speed: 2000 MHz
        Status: Populated, Enabled
        Upgrade: Other
        L1 Cache Handle: Not Provided
        L2 Cache Handle: Not Provided
        L3 Cache Handle: Not Provided
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Core Count: 3
        Core Enabled: 3
        Thread Count: 1
        Characteristics: None

Handle 0x1000, DMI type 16, 23 bytes
Physical Memory Array
        Location: Other
        Use: System Memory
        Error Correction Type: Multi-bit ECC
        Maximum Capacity: 2 GB
        Error Information Handle: Not Provided
        Number Of Devices: 1

Handle 0x1000, DMI type 16, 23 bytes
Physical Memory Array
        Location: Other
        Use: System Memory
        Error Correction Type: Multi-bit ECC
        Maximum Capacity: 2 GB
        Error Information Handle: Not Provided
        Number Of Devices: 1

Handle 0x1100, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x1000
        Error Information Handle: Not Provided
        Total Width: Unknown
        Data Width: Unknown
        Size: 2048 MB
        Form Factor: DIMM
        Set: None
        Locator: DIMM 0
        Bank Locator: Not Specified
        Type: RAM
        Type Detail: Other
        Speed: Unknown
        Manufacturer: QEMU
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Rank: Unknown
        Configured Clock Speed: Unknown
        Minimum Voltage:  Unknown
        Maximum Voltage:  Unknown
        Configured Voltage:  Unknown

Handle 0x1300, DMI type 19, 31 bytes
Memory Array Mapped Address
        Starting Address: 0x00000000000
        Ending Address: 0x0007FFFFFFF
        Range Size: 2 GB
        Physical Array Handle: 0x1000
        Partition Width: 1

Handle 0x2000, DMI type 32, 11 bytes
System Boot Information
        Status: No errors detected

Handle 0x7F00, DMI type 127, 4 bytes
End Of Table

Regards
jonas

**Comment by allangood** [comment]
Hi Jonas,

I really confused by the first line of plugin, why it returned "<<>>"?
Could you "cat" the detect_virtualization script, please?

Thank you.

**Comment by erdoking** [comment]
Really sorry, i worked in /tmp and after reboot there are no script anymore ...
but i find out the mistake!

It's a problem with github... if you do not check on the issue as a code remove Github the text by itself

<<<>>> as text
`<<<lnx_detect_virtual>>>` as code ...

**Comment by allangood** [comment]
LXC is not a virtualization, out of scope of this plugin.
